### ISSUE TITLE
DCMTK can't build do to conflict with ICU

### ISSUE THREAD

**Issue by JamesCTilton** [Slicer/SlicerBuildEnvironment#11] opened 2019-06-07 16:53 UTC
This is similar to DCMTK can't buid #10, but in that case the problem was something else besides a conflict with the system installed ICU.

The error I encounter in building Slicer is: 

[  2%] Linking CXX executable ../../bin/ofstd_tests
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_getFromUCallBack_50'
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_setToUCallBack_50'
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_close_50'
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_convertEx_50'
../../lib/libofstd.so.3.6.3: undefined reference to `u_errorName_50'
../../lib/libofstd.so.3.6.3: undefined reference to `UCNV_FROM_U_CALLBACK_SKIP_50'
../../lib/libofstd.so.3.6.3: undefined reference to `UCNV_TO_U_CALLBACK_SKIP_50'
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_setFromUCallBack_50'
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_open_50'
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_getName_50'
../../lib/libofstd.so.3.6.3: undefined reference to `UCNV_TO_U_CALLBACK_STOP_50'
../../lib/libofstd.so.3.6.3: undefined reference to `UCNV_FROM_U_CALLBACK_STOP_50'
collect2: error: ld returned 1 exit status
make[5]: *** [bin/ofstd_tests] Error 1
make[4]: *** [ofstd/tests/CMakeFiles/ofstd_tests.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [DCMTK-prefix/src/DCMTK-stamp/DCMTK-build] Error 2
make[1]: *** [CMakeFiles/DCMTK.dir/all] Error 2
make: *** [all] Error 2

Unlike the situation discussed in DCMTK can't buid #10, I do have a previously installed
version of ICU on my system (RedHat Linux version 7.6):

[jtilton@GSSDR17041094 ~]$ rpm -q -a | grep icu
libicu-devel-50.1.2-17.el7.x86_64
harfbuzz-icu-1.7.5-2.el7.x86_64
libicu-50.1.2-17.el7.x86_64

[jtilton@GSSDR17041094 ~]$ ls /usr/lib64/libicu*
/usr/lib64/libicudata.so         /usr/lib64/libicuio.so.50.1.2  /usr/lib64/libicutest.so.50
/usr/lib64/libicudata.so.50      /usr/lib64/libicule.so         /usr/lib64/libicutest.so.50.1.2
/usr/lib64/libicudata.so.50.1.2  /usr/lib64/libicule.so.50      /usr/lib64/libicutu.so
/usr/lib64/libicui18n.so         /usr/lib64/libicule.so.50.1.2  /usr/lib64/libicutu.so.50
/usr/lib64/libicui18n.so.50      /usr/lib64/libiculx.so         /usr/lib64/libicutu.so.50.1.2
/usr/lib64/libicui18n.so.50.1.2  /usr/lib64/libiculx.so.50      /usr/lib64/libicuuc.so
/usr/lib64/libicuio.so           /usr/lib64/libiculx.so.50.1.2  /usr/lib64/libicuuc.so.50
/usr/lib64/libicuio.so.50        /usr/lib64/libicutest.so       /usr/lib64/libicuuc.so.50.1.2

which apparently conflicts with:

[jtilton@GSSDR17041094 ~]$ ls /opt/Qt/5.12.3/gcc_64/lib/libicu*
/opt/Qt/5.12.3/gcc_64/lib/libicudata.so       /opt/Qt/5.12.3/gcc_64/lib/libiculx.so
/opt/Qt/5.12.3/gcc_64/lib/libicudata.so.56    /opt/Qt/5.12.3/gcc_64/lib/libiculx.so.56
/opt/Qt/5.12.3/gcc_64/lib/libicudata.so.56.1  /opt/Qt/5.12.3/gcc_64/lib/libiculx.so.56.1
/opt/Qt/5.12.3/gcc_64/lib/libicui18n.so       /opt/Qt/5.12.3/gcc_64/lib/libicutest.so
/opt/Qt/5.12.3/gcc_64/lib/libicui18n.so.56    /opt/Qt/5.12.3/gcc_64/lib/libicutest.so.56
/opt/Qt/5.12.3/gcc_64/lib/libicui18n.so.56.1  /opt/Qt/5.12.3/gcc_64/lib/libicutest.so.56.1
/opt/Qt/5.12.3/gcc_64/lib/libicuio.so         /opt/Qt/5.12.3/gcc_64/lib/libicutu.so
/opt/Qt/5.12.3/gcc_64/lib/libicuio.so.56      /opt/Qt/5.12.3/gcc_64/lib/libicutu.so.56
/opt/Qt/5.12.3/gcc_64/lib/libicuio.so.56.1    /opt/Qt/5.12.3/gcc_64/lib/libicutu.so.56.1
/opt/Qt/5.12.3/gcc_64/lib/libicule.so         /opt/Qt/5.12.3/gcc_64/lib/libicuuc.so
/opt/Qt/5.12.3/gcc_64/lib/libicule.so.56      /opt/Qt/5.12.3/gcc_64/lib/libicuuc.so.56
/opt/Qt/5.12.3/gcc_64/lib/libicule.so.56.1    /opt/Qt/5.12.3/gcc_64/lib/libicuuc.so.56.1

I've already tried setting my LD_LIBRARY_PATH to have the Qt version of the library appear first in my LD_LIBRARY_PATH - but I still get this same error.

How can I resolve this problem?

**Comment by JamesCTilton** [comment] 2019-06-09 02:27
I resolved this problem by putting the Qt pkgconfig directory in my PKG_CONFIG_PATH
environmental variable, so that I have:

PKG_CONFIG_PATH=/opt/Qt/5.12.3/gcc_64/lib/pkgconfig:/usr/local/lib64/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig

**Comment by jcfr** [comment] 2019-06-09 02:33
Well done.

To reproduce the original problem, could you share the command you are using to configure and build Slicer ? 

In the mean time, could you also submit a PR to improve the docker image ?

**Comment by JamesCTilton** [comment] 2019-06-09 20:27
This is the process I went through to build Slicer:

I followed the advice provided at:

https://www.slicer.org/wiki/Documentation/Nightly/Developers/Build_Instructions#BUILD_Slicer

for Linux. First I make sure my system satisfied the Linux Prerequisites:

CMake >= 3.13.4
Git >= 1.7.10
Svn >= 1.7
Qt 5.11: tested and recommended
GCC suite.

Since my system only had version 3.11.2 of cmake, I downloaded and installed the latest
available version of cmake (version 3.14.5). I needed to install cmake with the flag
-DCMAKE_US_OPENSSL=ON
I already had git version 1.8.3.1 and svn version 1.7.14 installed my computer.
I eventually ended up installing the latest available version of Qt (version 5.12.3)
using qt-unified-linux-x64-online.run (installed in /opt/Qt).
In my initial attempt to build Slicer, I did the following:

In my ~/Downloads directory, I performed the following commands:

git clone git://github.com/Slicer/Slicer.git
cd Slicer
./Utilities/SetupForDevelopment.sh
(answered the questions)
mkdir build
cd build
cmake -DQt5_DIR:PATH=/opt/Qt/5.11.3/gcc_64/lib/cmake/Qt5 ..
make

I got the error:

opt/Qt/5.11.3/gcc_64/bin/uic: relocation error: /opt/Qt/5.11.3/gcc_64/bin/uic: symbol _ZdlPvm, version Qt_5 not defined in file libQt5Core.so.5 with link time reference

I fixed this error by setting my environmental variables:

PATH=$HOME/bin:/opt/Qt/5.12.3/gcc_64:$PATH
Qt5_DIR=/opt/Qt/5.12.3/gcc_64/lib/cmake/Qt5

I deleted my previous ~/Downloads/Slicer directory and restarted the Slicer build from the beginning:

git clone git://github.com/Slicer/Slicer.git
cd Slicer
./Utilities/SetupForDevelopment.sh
(answered the questions)
mkdir build
cd build
cmake  ..
make

I then got the error I reported above:

[  4%] Linking CXX executable ../../bin/ofstd_tests
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_getFromUCallBack_50'
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_setToUCallBack_50'
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_close_50'
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_convertEx_50'
../../lib/libofstd.so.3.6.3: undefined reference to `u_errorName_50'
../../lib/libofstd.so.3.6.3: undefined reference to `UCNV_FROM_U_CALLBACK_SKIP_50'
../../lib/libofstd.so.3.6.3: undefined reference to `UCNV_TO_U_CALLBACK_SKIP_50'
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_setFromUCallBack_50'
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_open_50'
../../lib/libofstd.so.3.6.3: undefined reference to `ucnv_getName_50'
../../lib/libofstd.so.3.6.3: undefined reference to `UCNV_TO_U_CALLBACK_STOP_50'
../../lib/libofstd.so.3.6.3: undefined reference to `UCNV_FROM_U_CALLBACK_STOP_50'
collect2: error: ld returned 1 exit status
make[5]: *** [bin/ofstd_tests] Error 1
make[4]: *** [ofstd/tests/CMakeFiles/ofstd_tests.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [DCMTK-prefix/src/DCMTK-stamp/DCMTK-build] Error 2
make[1]: *** [CMakeFiles/DCMTK.dir/all] Error 2
make: *** [all] Error 2

As I reported above, I solved this problem by adding the Qt pkgconfig directory to my PKG_CONFIG_PATH definition:

PKG_CONFIG_PATH=/opt/Qt/5.12.3/gcc_64/lib/pkgconfig:/usr/local/lib64/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig

Again I deleted my previous ~/Downloads/Slicer directory and restarted the Slicer build from the beginning:

git clone git://github.com/Slicer/Slicer.git
cd Slicer
./Utilities/SetupForDevelopment.sh
(answered the questions)
mkdir build
cd build
cmake  ..
make

Slicer built with no errors this time (but with some warnings)

I've also run ctests on my Slicer build with the following result:

81% tests passed, 128 tests failed out of 666

I don't know it the failed tests will be of any consequence to me.
The tests that failed are:

The following tests FAILED:
	 17 - py_vtkITKArchetypeDiffusionTensorReaderFile (Failed)
	 18 - py_vtkITKArchetypeScalarReaderFile (Failed)
	161 - vtkMRMLCameraDisplayableManagerTest1 (Failed)
	189 - qMRMLMatrixWidgetTest1 (Failed)
	231 - qMRMLVolumeInfoWidgetTest1 (Failed)
	247 - qMRMLMatrixWidgetEventTranslatorPlayerTest1 (Failed)
	259 - qMRMLVolumeInfoWidgetEventTranslatorPlayerTest1 (Failed)
	275 - qSlicerSslTest (Failed)
	294 - qSlicerPyCLIModuleTest1 (Failed)
	315 - py_ColorsScalarBarSelfTest (Failed)
	316 - py_CustomColorTableSceneViewRestoreTestBug3992 (Failed)
	346 - py_AnnotationsTestingAddManyFiducials (Failed)
	347 - py_AnnotationsTestingAddManyRulers (Failed)
	348 - py_AnnotationsTestingAddManyROIs (Failed)
	349 - py_RemoveAnnotationsIDFromSelectionNode (Failed)
	350 - py_LoadAnnotationRulerScene (Failed)
	351 - py_AnnotationsTestingFiducialWithSceneViewRestore (Failed)
	355 - py_MarkupsWidgetsSelfTest (Failed)
	367 - vtkMarkupsAnnotationSceneTest (Failed)
	368 - py_AddManyMarkupsFiducialTest (Failed)
	369 - py_MarkupsSceneViewRestoreTestSimple (Failed)
	370 - py_MarkupsSceneViewRestoreTestManyLists (Failed)
	371 - py_NeurosurgicalPlanningTutorialMarkupsSelfTest (Failed)
	372 - py_MarkupsInCompareViewersSelfTest (Failed)
	373 - py_MarkupsInViewsSelfTest (Failed)
	374 - qSlicerTransformsModuleGenericTest (Failed)
	375 - qSlicerTransformsModuleWidgetGenericTest (Failed)
	381 - qSlicerTransformsModuleWidgetTest (Failed)
	392 - qSlicerModelsModuleWidgetTest1 (Failed)
	393 - qSlicerModelsModuleWidgetTestScene (Failed)
	399 - py_PlotsSelfTest (Failed)
	404 - py_AddStorableDataAfterSceneViewTest (Failed)
	407 - py_nomainwindow_SegmentationsModuleTest1 (Failed)
	408 - py_nomainwindow_SegmentationWidgetsTest1 (Failed)
	415 - py_TablesSelfTest (Failed)
	420 - qSlicerVolumesModuleGenericTest (Failed)
	421 - qSlicerVolumesModuleWidgetGenericTest (Failed)
	425 - qSlicerVolumesIOOptionsWidgetTest1 (Failed)
	426 - qSlicerVolumesModuleWidgetTest1 (Failed)
	430 - py_LoadVolumeDisplaybleSceneModelClose (Failed)
	431 - py_VolumesLogicCompareVolumeGeometry (Failed)
	444 - vtkMRMLVolumeRenderingMultiVolumeTest (Failed)
	445 - py_VolumeRenderingSceneClose (Failed)
	446 - py_VolumeRenderingThreeDOnlyLayout (Failed)
	450 - py_CropVolumeSelfTest (Failed)
	451 - py_nomainwindow_qSlicerDataProbeModuleGenericTest (Failed)
	452 - py_nomainwindow_qSlicerEditorModuleGenericTest (Failed)
	453 - py_ThresholdThreadingTest (Failed)
	454 - py_StandaloneEditorWidgetTest (Failed)
	455 - py_nomainwindow_qSlicerLabelStatisticsModuleGenericTest (Failed)
	456 - py_LabelStatistics (Failed)
	457 - py_nomainwindow_qSlicerPerformanceTestsModuleGenericTest (Failed)
	458 - py_PerformanceTests (Failed)
	459 - py_nomainwindow_qSlicerSampleDataModuleGenericTest (Failed)
	460 - py_SampleData (Failed)
	461 - py_nomainwindow_qSlicerScreenCaptureModuleGenericTest (Failed)
	462 - py_ScreenCapture (Failed)
	463 - py_SegmentEditor (Failed)
	464 - py_nomainwindow_qSlicerSegmentStatisticsModuleGenericTest (Failed)
	465 - py_SegmentStatistics (Failed)
	466 - py_nomainwindow_qSlicerSelfTestsModuleGenericTest (Failed)
	467 - py_nomainwindow_qSlicerSurfaceToolboxModuleGenericTest (Failed)
	468 - py_nomainwindow_qSlicerVectorToScalarVolumeModuleGenericTest (Failed)
	469 - py_nomainwindow_qSlicerDMRIInstallModuleGenericTest (Failed)
	470 - py_nomainwindow_qSlicerExtensionWizardModuleGenericTest (Failed)
	471 - py_nomainwindow_qSlicerEndoscopyModuleGenericTest (Failed)
	472 - py_nomainwindow_qSlicerDICOMModuleGenericTest (Failed)
	473 - py_nomainwindow_qSlicerDICOMPatcherModuleGenericTest (Failed)
	474 - py_DICOMPatcher (Failed)
	557 - qSlicerAppMainWindowTest1 (Failed)
	570 - py_nomainwindow_SlicerTestingExitSuccessTest (Failed)
	572 - py_SlicerTestingExitSuccessTest (Failed)
	576 - py_nowarning_mainwindowTest (Failed)
	577 - py_nowarning_mainwindow_application_infoTest (Failed)
	578 - py_nowarning_mainwindow_python_interactorTest (Failed)
	579 - py_nowarning_mainwindow_nocliTest (Failed)
	580 - py_nowarning_mainwindow_noloadableTest (Failed)
	582 - py_nowarning_mainwindow_nocli_noloadableTest (Failed)
	587 - py_nowarning_nomainwindowTest (Failed)
	588 - py_nowarning_nomainwindow_application_infoTest (Failed)
	589 - py_nowarning_nomainwindow_python_interactorTest (Failed)
	590 - py_nowarning_nomainwindow_nocliTest (Failed)
	591 - py_nowarning_nomainwindow_noloadableTest (Failed)
	593 - py_nowarning_nomainwindow_nocli_noloadableTest (Failed)
	598 - py_nowarning_nomainwindow_ignoreslicerrcTest (Failed)
	603 - py_nomainwindow_ScriptedModuleDiscoveryTest (Failed)
	607 - py_mainwindow_MRMLSceneImportAndExport (Failed)
	608 - py_nomainwindow_test_sitkUtils (Failed)
	616 - py_nomainwindow_DWMRIMultishellIOTests (Failed)
	624 - py_AtlasTests (Failed)
	625 - py_DICOMReaders (Failed)
	626 - py_KneeAtlasTest (Failed)
	627 - py_sceneImport2428 (Failed)
	628 - py_SlicerMRBMultipleSaveRestoreLoopTest (Failed)
	629 - py_SlicerMRBMultipleSaveRestoreTest (Failed)
	630 - py_SlicerMRBSaveRestoreCheckPathsTest (Failed)
	631 - py_Slicer4Minute (Failed)
	632 - py_SlicerBoundsTest (Failed)
	633 - py_Charting (Failed)
	634 - py_WebEngine (Failed)
	635 - py_SliceLinkLogic (Failed)
	636 - py_ScenePerformance (Failed)
	637 - py_SlicerCreateRulerCrashIssue4199 (Failed)
	638 - py_SlicerRestoreSceneViewCrashIssue3445 (Failed)
	639 - py_RSNAVisTutorial (Failed)
	640 - py_RSNAQuantTutorial (Failed)
	641 - py_slicerCloseCrashBug2590 (Failed)
	642 - py_SlicerOrientationSelectorTest (Failed)
	643 - py_SlicerTransformInteractionTest1 (Failed)
	644 - py_UtilTest (Failed)
	645 - py_ViewControllersSliceInterpolationBug1926 (Failed)
	646 - py_RSNA2012ProstateDemo (Failed)
	647 - py_JRC2013Vis (Failed)
	648 - py_FiducialLayoutSwitchBug1914 (Failed)
	649 - py_SubjectHierarchyGenericSelfTest (Failed)
	650 - py_SubjectHierarchyCorePluginsSelfTest (Failed)
	651 - py_ShaderProperties (Failed)
	652 - py_CLIEventTest (Failed)
	653 - py_TwoCLIsInARowTest (Failed)
	654 - py_TwoCLIsInParallelTest (Failed)
	655 - py_BRAINSFitRigidRegistrationCrashIssue4139 (Failed)
	656 - py_nomainwindow_qSlicerMultiVolumeImporterModuleGenericTest (Failed)
	657 - py_nomainwindow_qSlicerSimpleFiltersModuleGenericTest (Failed)
	658 - py_SimpleFiltersModuleTest (Failed)
	663 - py_CompareVolumes (Failed)
	664 - py_nomainwindow_qSlicerLandmarkRegistrationModuleGenericTest (Failed)
	665 - py_LandmarkRegistration (Failed)
	666 - PythonSlicerSimpleNUMPYTest (Failed)
Errors while running CTest

I have no idea how to "submit a PR to improve the docker image".
I would be happy to do so if you would provide me with explicit instructions on how to do this

**Comment by jcfr** [comment] 2019-06-10 17:18
Thanks for the detailed explanation.

Based on what you reported, it looks like you are building Slicer directly on your workstation **without** using the docker image described in this repository. 

Am I correctly understanding ?

**Comment by JamesCTilton** [comment] 2019-06-10 17:50
Since I don’t understand how to use the docker image, I built Slicer directly on my workstation.

**Comment by jcfr** [comment] 2019-06-10 18:03
> Since I don’t understand how to use the docker image, I built Slicer directly on my workstation.

I see. To move forward with addressing the build issues related to building on your workstation, I suggest you move that discussion into the forum: https://discourse.slicer.org/c/dev

That way, answers will benefit everyone.




> I don’t understand how to use the docker image

The docker image bundles cmake, git, compiler and qt libraries we use to build Slicer every day on Linux. 

For example, to build and package the latest Slicer, you would do the following:

```
docker run --rm slicer/buildenv-qt5-centos7 > ~/bin/slicer-buildenv-qt5-centos7
chmod u+x ~/bin/slicer-buildenv-qt5-centos7

# Download Slicer sources
git clone git://github.com/Slicer/Slicer

# Configure Slicer
slicer-buildenv-qt5-centos7 cmake \
  -BSlicer-build -HSlicer \
  -GNinja \
  -DCMAKE_BUILD_TYPE:STRING=Release \
  -DBUILD_TESTING:BOOL=OFF

# Build Slicer
slicer-buildenv-qt5-centos7 cmake --build Slicer-build

# Package Slicer
slicer-buildenv-qt5-centos7 cmake --build Slicer-build/Slicer-build --target package
```

**Comment by JamesCTilton** [comment] 2019-06-10 18:23
Thank you for your advice.

My eventual goal is to develop an application (in C++) that utilizes the 3D visualization capabilities of Slicer
to allow an analyst to interactively label a 3D image segmentation (produced externally to Slicer by an image
segmentation approach of my own design).

Can (or should) I do this within the docker environment – or can (or should) I continue to work independently of the
docker environment on my workstation?

Jim Tilton

________________________________
Dr. James C. Tilton                                               Voice:   301-286-9510
NASA Goddard Space Flight Center                   FAX:     301-286-1776
Mail Code 606.3                                                    E-Mail:  James.C.Tilton@nasa.gov<mailto:James.C.Tilton@nasa.gov>
(Computational & Information Sciences and Technology Office)
Greenbelt, MD 20771
URL: http://science.gsfc.nasa.gov/sed/bio/james.c.tilton

**Comment by jcfr** [comment] 2019-06-10 18:42
### development vs distribution

There are two aspects to consider:

(1) developing the application. Which I recommend to do directly on your workstation so that you can use your favorite IDE, text editor, etc ... 

(2) Packaging and distributing the application so that it can be installed on a board set of linux distributions.

### custom segmentation approach

> an image segmentation approach of my own design

This is great, the 3D Slicer segmentation editor can be extended with you own segmentation effect. Depending on what you are trying to achieve, you could also look at extending ITK.

Then, after created your own effect, it could be distributed as a Slicer extension available for anyone or package in a custom application

I suggest we continue the discussion by email, I can be reached at jcfr@kitware.com

**Comment by jcfr** [comment] 2020-05-28 18:10
Closing. Do not hesitate to ask question on the forum if you need more help. See https://discourse.slicer.org/

**Closed by jcfr** 2020-05-28 18:10 UTC
